FROM ghcr.io/aservo/helmfile:latest

# Run noninteractive

ARG DEBIAN_FRONTEND=noninteractive

# Install packages

RUN \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

# Install main packages

RUN \
    apt-get update && \
    apt-get install -y containerd.io docker-ce docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install PIP packages

ARG AZ_VERSION=2.34.1
RUN pip3 install -Iv azure-cli==${AZ_VERSION}
