name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  build:

    name: Build Image

    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.release.tag_name }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set tag for non-release builds
        if: github.event_name != 'release'
        run: |
          echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        # don't even login to GitHub CR if this is not a release 
        if: github.event_name == 'release'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build / Release
        uses: docker/build-push-action@v2
        with:
          load: true
          push: ${{ github.event_name == 'release' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/helmfile:latest
            ghcr.io/${{ github.repository_owner }}/helmfile:${{ env.TAG }}

      - name: Inspect
        run: |
          docker image inspect ghcr.io/${{ github.repository_owner }}/helmfile:latest
